//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diskplot.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("diskplot.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to continue? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ask_continue {
            get {
                return ResourceManager.GetString("ask_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cancel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom Icon benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string customicon {
            get {
                return ResourceManager.GetString("customicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Debugging benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string debuginfo {
            get {
                return ResourceManager.GetString("debuginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   delete benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All plots, settings and others will be deleted. This option won&apos;t delete any files or folders in your disk. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string delete_fresh {
            get {
                return ResourceManager.GetString("delete_fresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All files in this plot WILL BE DELETED FOREVER. You can&apos;t undo this action. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string delete_plot {
            get {
                return ResourceManager.GetString("delete_plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Plot benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string delete_plot_title {
            get {
                return ResourceManager.GetString("delete_plot_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All plots, settings and others will be deleted. This will uninstall DiskPlot, but it won&apos;t affect your files. Folders will be stay in your disk. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string delete_uninstall {
            get {
                return ResourceManager.GetString("delete_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string directory {
            get {
                return ResourceManager.GetString("directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Folder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string diskplot_current {
            get {
                return ResourceManager.GetString("diskplot_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main Folder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string diskplot_main {
            get {
                return ResourceManager.GetString("diskplot_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documents benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This icon is used by DiskPlot and can&apos;t be deleted. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string error_cantdelete {
            get {
                return ResourceManager.GetString("error_cantdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This icon already added to icon library. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string error_icon {
            get {
                return ResourceManager.GetString("error_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is a problem with DiskPlot folder. Please make sure to don&apos;t delete DiskPlot folder. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string error_launch {
            get {
                return ResourceManager.GetString("error_launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string error_launch_title {
            get {
                return ResourceManager.GetString("error_launch_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This plot has been lost, plot folder may be moved or deleted from your disk. Please take back that folder to DiskPlot folder with same name. Or delete this plot completely. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string error_lost {
            get {
                return ResourceManager.GetString("error_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnected Plot benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string error_lost_title {
            get {
                return ResourceManager.GetString("error_lost_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A plot name is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string error_name {
            get {
                return ResourceManager.GetString("error_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plot directory and name can&apos;t be same with other plots. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string error_same {
            get {
                return ResourceManager.GetString("error_same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This plot name is using by DiskPlot itself. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string error_system {
            get {
                return ResourceManager.GetString("error_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error. Normally, DiskPlot detects common problems, but now DiskPlot have problems to detect it. Please try again later. Error details can be found below: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string error_unexpected {
            get {
                return ResourceManager.GetString("error_unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fresh Reset benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string fresh_reset {
            get {
                return ResourceManager.GetString("fresh_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icons benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string icons {
            get {
                return ResourceManager.GetString("icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Limit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string limit {
            get {
                return ResourceManager.GetString("limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add limit to your plot if you want to comparise the other plots, or to track size usage. You can still exceed the limit with files. Also you don&apos;t need to set a limit. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string limitinfo {
            get {
                return ResourceManager.GetString("limitinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This plot has been lost. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lost {
            get {
                return ResourceManager.GetString("lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   lost benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lost_lbl {
            get {
                return ResourceManager.GetString("lost_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   open benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string open_lbl {
            get {
                return ResourceManager.GetString("open_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performance Mode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string performance {
            get {
                return ResourceManager.GetString("performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plot benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string plot {
            get {
                return ResourceManager.GetString("plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plots benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string plots {
            get {
                return ResourceManager.GetString("plots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   save benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uninstall DiskPlot benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string uninstall {
            get {
                return ResourceManager.GetString("uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You won&apos;t able to create plots with the same name of current plot names since directories won&apos;t be deleted. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string warning_fresh {
            get {
                return ResourceManager.GetString("warning_fresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DiskPlot will be removed from this drive. Your plots and files will stay in your disk, but you need to install DiskPlot again to manage them. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string warning_uninstall {
            get {
                return ResourceManager.GetString("warning_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Website benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Organize your files. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DiskPlot allows organizing your files by creating virtual plots in your disk. Also, you can attach an icon and name to your plots. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string welcome1 {
            get {
                return ResourceManager.GetString("welcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can create as much plot as you want. And your plots are fast and safe because they are not hardware based. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string welcome2 {
            get {
                return ResourceManager.GetString("welcome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your disk, your rules. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string welcome3 {
            get {
                return ResourceManager.GetString("welcome3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your homeworks, documents, photos... may take up more space than you think. Specify a plot size to measure how much space your plot uses. In this way, track the plot usage with a progress bar. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string welcome4 {
            get {
                return ResourceManager.GetString("welcome4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your documents benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yourdocuments {
            get {
                return ResourceManager.GetString("yourdocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your photos benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yourphotos {
            get {
                return ResourceManager.GetString("yourphotos", resourceCulture);
            }
        }
    }
}
